### ISSUE TITLE
eth holders to add

### ISSUE THREAD

**Issue by hanniabu** [ethismoney-xyz/data#2]
Royal Government of Bhutan
https://intel.arkm.com/explorer/entity/druk-holding-investments

unsure of addresses, would be good to crawl company holdings to have an updated list since I know for a fact this isn't updated since Meitu disclosed having around 68k ETH
https://www.coingecko.com/en/public-companies-ethereum

**Comment by hanniabu** [comment]
https://www.accesswire.com/943902/cosmos-health-integrates-bitcoin-and-ethereum-as-treasury-reserve-assets

**Comment by mseidlx** [comment]
@hanniabu would be great if you could create a PR to the eth_holders.yml file with the wallet addresses (for onchain tracking) or adding individual transactions similar to the Michigan Pension fund we are tracking (for offchain tracking).

If anything seems unclear please let us know so that we can improve the process!

**Comment by mseidlx** [comment]
merged your PR (https://github.com/ethismoney-xyz/data/pull/3)
would be great to create additional PRs for any holder to add
